import { Inter } from "next/font/google";
import "./globals.css";
import { ColorSchemeScript } from "@mantine/core";
import { Providers } from "./providers";
import { BasicAppShell } from "@/components/BasicAppShell";
// import AppShellComp from "@/components/AppShellComp";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        <Providers>
          <BasicAppShell children={children}/>
        </Providers>
      </body>
    </html>
  );
}
